### ISSUE TITLE
Gulp doesnt work.

### ISSUE THREAD

**Issue by Cst2989** [StephenGrider/ReactCasts#10]
Here is the error that i`m getting : 

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch Y:\dan-testing\site\ReactWorkspace\thumbnail-list\node_modules\react\lib\ExecutionEnvironment.js UNKNOWN
    at exports._errnoException (util.js:874:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (Y:\dan-testing\site\ReactWorkspace\thumbnail-list\node_modules\watchify\node_modules\chokidar\lib\nodefs-handler.js:24:15)
    at setFsWatchListener (Y:\dan-testing\site\ReactWorkspace\thumbnail-list\node_modules\watchify\node_modules\chokidar\lib\nodefs-handler.js:47:19)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (Y:\dan-testing\site\ReactWorkspace\thumbnail-list\node_modules\watchify\node_modules\chokidar\lib\nodefs-handler.js:177:15)
    at EventEmitter.NodeFsHandler._handleFile (Y:\dan-testing\site\ReactWorkspace\thumbnail-list\node_modules\watchify\node_modules\chokidar\lib\nodefs-handler.js:201:8)
    at EventEmitter.<anonymous> (Y:\dan-testing\site\ReactWorkspace\thumbnail-list\node_modules\watchify\node_modules\chokidar\lib\nodefs-handler.js:353:12)
    at FSReqWrap.oncomplete (fs.js:82:15)

The gulpfile.js other files and package.json are the same as yours.

**Comment by Certiman** [comment]
On windows, the atom-npm pair resulted in errors. Since I'm using Brackets.io and "npm install --save" before running gulp, everything works great, including the auto-reloading.
