### ISSUE TITLE
Couldn't start gulp with ReactStart

### ISSUE THREAD

**Issue by antiperfectclub** [StephenGrider/ReactCasts#2]
Hello, 
I checkout the reactstart repo and I cannot have gulp working. 

---

fs.js:1063
    throw errnoException(process._errno, 'watch');
          ^
Error: watch EMFILE
    at errnoException (fs.js:1031:11)
    at FSWatcher.start (fs.js:1063:11)
    at Object.fs.watch (fs.js:1088:11)
    at watch (/Users/ChloeGyuriKim/Desktop/Webproject/React/ReactTutorial_Stephen_Grider/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:221:8)
    at /Users/ChloeGyuriKim/Desktop/Webproject/React/ReactTutorial_Stephen_Grider/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:230:9
    at /Users/ChloeGyuriKim/Desktop/Webproject/React/ReactTutorial_Stephen_Grider/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:41:14
    at Array.forEach (native)
    at /Users/ChloeGyuriKim/Desktop/Webproject/React/ReactTutorial_Stephen_Grider/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:38:18
    at ReaddirReq.Req.done (/Users/ChloeGyuriKim/Desktop/Webproject/React/ReactTutorial_Stephen_Grider/ReactStarter/node_modules/gulp-watch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:143:5)
    at ReaddirReq.done (/Users/ChloeGyuriKim/Desktop/Webproject/React/ReactTutorial_Stephen_Grider/ReactStarter/node_modules/gulp-watch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:90:22)

---

I am so stuck at firebase chapter :/ Plz help me to solve this.

Thank you so much in advance!

Cheers,
CK

**Comment by mixophrygian** [comment]
+1 same issue, cloned ReactCasts today, cd'd into imgur-client, npm install'd, gulp'd and then got:

```
[09:08:42] Using gulpfile ~/Desktop/personal/ReactUdemy/ReactCasts/imgur-client/gulpfile.js
[09:08:42] Starting 'build'...
[09:08:42] Finished 'build' after 8.12 ms
[09:08:42] Starting 'serve'...
[09:08:42] Starting 'sass'...
[09:08:42] Finished 'sass' after 3.95 ms
[09:08:42] Starting 'watch'...
[09:08:42] Finished 'watch' after 8.21 ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)
```

**Comment by bloolizard** [comment]
bump, having same issue.

**Comment by SOSANA** [comment]
@ChloeKim still having problems? Check out my repo if you need to look at another working example from Stephan's work shop. https://github.com/SOSANA/React.JS-Tutorials-and-Things/tree/master/buildWebAppsWithReactJSAndFlux/section5

I'm on lecture 30, you should also be able to cd into src and do a git checkout by copying the sha (this is beggining for fire base chapter)
Git checkout 2ca16df611e4e532899dad5e6caf70f06e684965

I put a notes file regarding npm install etc as well in my repo.

**Comment by bloolizard** [comment]
Might be because of an issue using OS X Yosemite 10.10.4 .  Switched to my Windows system and was able to run without error.

**Comment by kovacs** [comment]
bump, same same... I'm on Mavericks

**Comment by christopherhuii** [comment]
Having the same issue. Not sure what to do. Running on OS X 10.10.5
@StephenGrider
